import type { Metadata } from "next";
import { Reddit_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const redditSans = Reddit_Sans({
  variable: "--reddit-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${redditSans.variable}  antialiased `}>
        <main className="mx-4 mt-8 mb-20 md:mt-10 md:mx-8 lg:max-w-[1170px] lg:mx-auto ">
          {children}
        </main>
      </body>
    </html>
  );
}
