import IconBudgets from "../svg/IconBudgets";
import IconOverview from "../svg/IconOverview";
import IconPots from "../svg/IconPots";
import IconRecurringBills from "../svg/IconRecurringBills";
import IconTransactions from "../svg/IconTransactions";
import {
	Activity,
	Apple,
	Briefcase,
	Bus,
	CircleDollarSign,
	Coffee,
	Dog,
	Dumbbell,
	Gift,
	Heart,
	HeartPlus,
	Hexagon,
	Lightbulb,
	Phone,
	Plane,
	Settings,
	ShoppingCart,
	Star,
	TentTree,
	Theater,
	Wallet,
} from "lucide-react";
import Home from "@/app/page";
import IconSettings from "../svg/IconSettings";
import {
	CategoriesType,
	CurrencyType,
	NavLink,
	ProfileIconType,
	ThemeType,
	TransactionType,
} from "./types";

export const Themes: ThemeType[] = [
	{
		name: "Green",
		id: "green",
		value: "#277C78",
	},
	{
		name: "Yellow",
		id: "yellow",
		value: "#F2CDAC",
	},
	{
		name: "Cyan",
		id: "cyan",
		value: "#82C9D7",
	},
	{
		name: "Navy",
		id: "navy",
		value: "#626070",
	},
	{
		name: "Red",
		id: "red",
		value: "#C94736",
	},
	{
		name: "Purple",
		id: "purple",
		value: "#826CB0",
	},
	{
		name: "Light Purple",
		id: "light-purple",
		value: "#AF81BA",
	},
	{
		name: "Turquoise",
		id: "turquoise",
		value: "#597C7C",
	},
	{
		name: "Brown",
		id: "brown",
		value: "#93674F",
	},
	{
		name: "Magenta",
		id: "magenta",
		value: "#934F6F",
	},
	{
		name: "Sky Blue",
		id: "sky-blue",
		value: "#3F82B2",
	},
	{
		name: "Navy Grey",
		id: "navy-grey",
		value: "#97A0AC",
	},
	{
		name: "Army Green",
		id: "army-green",
		value: "#7F9161",
	},
	{
		name: "Gold",
		id: "gold",
		value: "#CAB361",
	},
	{
		name: "Orange",
		id: "orange",
		value: "#BE6C49",
	},
];

export const iconMap = {
	Apple,
	Bus,
	Theater,
	Activity,
	HeartPlus,
	Wallet,
	Settings,
	Dog,
	Hexagon,
	Phone,
	Heart,
	CircleDollarSign,
	Coffee,
	Star,
	ShoppingCart,
	Plane,
	Home,
	Briefcase,
	Lightbulb,
	Gift,
	Dumbbell,
	TentTree,
};
export const CategoryIcons: (keyof typeof iconMap)[] = [
	"Apple",
	"Bus",
	"Theater",
	"Activity",
	"HeartPlus",
	"Wallet",
	"Dog",
	"Hexagon",
	"Phone",
	"Heart",
	"CircleDollarSign",
	"Coffee",
	"Star",
	"ShoppingCart",
	"Plane",
	"Briefcase",
	"Lightbulb",
	"Gift",
	"Dumbbell",
	"TentTree",
] as (keyof typeof iconMap)[];

export const defaultCategories: CategoriesType[] = [
	{ name: "Food", icon: "Apple" },
	{ name: "Transport", icon: "Bus" },
	{ name: "Entertainment", icon: "Theater" },
	{ name: "Health", icon: "Activity" },
	{ name: "Shopping", icon: "HeartPlus" },
	{ name: "Bills", icon: "Wallet" },
	{ name: "Other", icon: "" },
];

export const defaultTransactions: TransactionType[] = [
	{
		title: "Grocery Shopping",
		category: { name: "Food", icon: "Apple" },
		date: new Date("2025-05-01").toISOString(),
		amount: 150.75,
		type: "expense",
		reccuring: false,
		id: "grocery-shopping-1",
	},
	{
		title: "Salary",
		category: { name: "Income", icon: "Wallet" },
		date: new Date("2025-05-01").toISOString(),
		amount: 3000,
		type: "income",
		reccuring: true,
		id: "salary-1",
	},
	{
		title: "Bus Ticket",
		category: { name: "Transport", icon: "Bus" },
		date: new Date("2025-05-02").toISOString(),
		amount: 2.5,
		type: "expense",
		reccuring: false,
		id: "bus-ticket-1",
	},
	{
		title: "Movie Night",
		category: { name: "Entertainment", icon: "Theater" },
		date: new Date("2025-05-03").toISOString(),
		amount: 12.99,
		type: "expense",
		reccuring: false,
		id: "movie-night-1",
	},
	{
		title: "Gym Membership",
		category: { name: "Health", icon: "Activity" },
		date: new Date("2025-05-01").toISOString(),
		amount: 50,
		type: "expense",
		reccuring: true,
		id: "gym-membership-1",
	},
	{
		title: "Online Shopping",
		category: { name: "Shopping", icon: "HeartPlus" },
		date: new Date("2025-05-05").toISOString(),
		amount: 120.45,
		type: "expense",
		reccuring: false,
		id: "online-shopping-1",
	},
	{
		title: "Electricity Bill",
		category: { name: "Bills", icon: "Wallet" },
		date: new Date("2025-05-03").toISOString(),
		amount: 75.89,
		type: "expense",
		reccuring: true,
		id: "electricity-bill-1",
	},
	{
		title: "Concert Tickets",
		category: { name: "Entertainment", icon: "Theater" },
		date: new Date("2025-05-07").toISOString(),
		amount: 200,
		type: "expense",
		reccuring: false,
		id: "concert-tickets-1",
	},
	{
		title: "Coffee with Friends",
		category: { name: "Food", icon: "Apple" },
		date: new Date("2025-05-08").toISOString(),
		amount: 15.25,
		type: "expense",
		reccuring: false,
		id: "coffee-with-friends-1",
	},
	{
		title: "Car Maintenance",
		category: { name: "Transport", icon: "Bus" },
		date: new Date("2025-05-09").toISOString(),
		amount: 300,
		type: "expense",
		reccuring: false,
		id: "car-maintenance-1",
	},
	{
		title: "Freelance Project",
		category: { name: "Income", icon: "Wallet" },
		date: new Date("2025-05-05").toISOString(),
		amount: 500,
		type: "income",
		reccuring: false,
		id: "freelance-project-1",
	},
	{
		title: "Pharmacy Purchase",
		category: { name: "Health", icon: "Activity" },
		date: new Date("2025-06-11").toISOString(),
		amount: 25.5,
		type: "expense",
		reccuring: false,
		id: "pharmacy-purchase-1",
	},
	{
		title: "Streaming Subscription",
		category: { name: "Entertainment", icon: "Theater" },
		date: new Date("2025-05-12").toISOString(),
		amount: 9.99,
		type: "expense",
		reccuring: true,
		id: "streaming-subscription-1",
	},
	{
		title: "Lunch at Restaurant",
		category: { name: "Food", icon: "Apple" },
		date: new Date("2025-05-13").toISOString(),
		amount: 45.75,
		type: "expense",
		reccuring: false,
		id: "lunch-at-restaurant-1",
	},
	{
		title: "Clothing Purchase",
		category: { name: "Shopping", icon: "HeartPlus" },
		date: new Date("2025-05-14").toISOString(),
		amount: 150,
		type: "expense",
		reccuring: false,
		id: "clothing-purchase-1",
	},
	{
		title: "Water Bill",
		category: { name: "Bills", icon: "Wallet" },
		date: new Date("2025-05-15").toISOString(),
		amount: 30.25,
		type: "expense",
		reccuring: true,
		id: "water-bill-1",
	},
	{
		title: "Book Purchase",
		category: { name: "Entertainment", icon: "Theater" },
		date: new Date("2025-06-16").toISOString(),
		amount: 20,
		type: "expense",
		reccuring: false,
		id: "book-purchase-1",
	},
	{
		title: "Van Hire",
		category: { name: "Transport", icon: "Bus" },
		date: new Date("2025-06-02").toISOString(),
		amount: 60,
		type: "expense",
		reccuring: false,
		id: "vah-hire-1",
	},
	{
		title: "Dinner with Family",
		category: { name: "Food", icon: "Apple" },
		date: new Date("2025-05-17").toISOString(),
		amount: 80,
		type: "expense",
		reccuring: false,
		id: "dinner-with-family-1",
	},
	{
		title: "Pet Supplies",
		category: { name: "Shopping", icon: "HeartPlus" },
		date: new Date("2025-06-18").toISOString(),
		amount: 60.5,
		type: "expense",
		reccuring: false,
		id: "pet-supplies-1",
	},
	{
		title: "Internet Bill",
		category: { name: "Bills", icon: "Wallet" },
		date: new Date("2025-05-19").toISOString(),
		amount: 50,
		type: "expense",
		reccuring: true,
		id: "internet-bill-1",
	},
	{
		title: "Yoga Class",
		category: { name: "Health", icon: "Activity" },
		date: new Date("2025-06-20").toISOString(),
		amount: 25,
		type: "expense",
		reccuring: false,
		id: "yoga-class-1",
	},
];

export const sortByOptions = ["Latest", "Oldest", "A to Z", "Z to A", "Highest", "Lowest"];

export const navlinks: NavLink[] = [
	{
		title: "Overview",
		link: "/",
		icon: IconOverview,
	},
	{
		title: "Transactions",
		link: "/transactions",
		icon: IconTransactions,
	},
	{
		title: "Budgets",
		link: "/budgets",
		icon: IconBudgets,
	},
	{
		title: "Pots",
		link: "/pots",
		icon: IconPots,
	},
	{
		title: "Recurring bills",
		link: "/recurring-bills",
		icon: IconRecurringBills,
	},
	{
		title: "Settings",
		link: "/settings",
		icon: IconSettings,
	},
];

export const profileIcons: ProfileIconType[] = [
	{
		iconSrc: "/icons/down-arrow.png",
		alt: "Person holding a down arrow",
		title: "Person holding a down arrow",
	},
	{
		iconSrc: "/icons/equilibrium.png",
		alt: "Person on a balance scale",
		title: "Person on a balance scale",
	},
	{
		iconSrc: "/icons/formula.png",
		alt: "Person showing a formula",
		title: "Person showing a formula",
	},
	{
		iconSrc: "/icons/growMoney.png",
		alt: "Person watering a money plant",
		title: "Person watering a money plant",
	},
	{
		iconSrc: "/icons/waitingGrowth.png",
		alt: "Person waiting for growth",
		title: "Person waiting for growth",
	},
	{
		iconSrc: "/icons/growth.png",
		alt: "Person sitting on money with an arrow pointing up",
		title: "Person sitting on money with an arrow pointing up",
	},
	{
		iconSrc: "/icons/growthWalkUp.png",
		alt: " Person walking up a growth chart",
		title: "Person walking up a growth chart",
	},
	{
		iconSrc: "/icons/growthUp.png",
		alt: "Person showing growth up",
		title: "Person showing growth up",
	},
	{
		iconSrc: "/icons/growthArrow.png",
		alt: "Person shoiwng groeth close up",
		title: "Person showing growth close up",
	},
	{
		iconSrc: "/icons/inflation.png",
		alt: "Person wondering about inflation",
		title: "Person wondering about inflation",
	},
	{
		iconSrc: "/icons/investigation.png",
		alt: "Person investigating chart",
		title: "Person investigating chart",
	},
	{
		iconSrc: "/icons/money-exchange.png",
		alt: "Person turning a coin",
		title: "Person turning a coin",
	},
	{
		iconSrc: "/icons/pie-chart.png",
		alt: "Person showing a pie chart",
		title: "Person showing a pie chart",
	},
	{
		iconSrc: "/icons/piggy-bank.png",
		alt: "Person putting money in a piggy bank",
		title: "Person putting money in a piggy bank",
	},
	{
		iconSrc: "/icons/piggy-bankHold.png",
		alt: "Person holding a piggy bank",
		title: "Person holding a piggy bank",
	},
	{
		iconSrc: "/icons/save-coin.png",
		alt: "Person holding a coin",
		title: "Person holding a coin",
	},
	{
		iconSrc: "/icons/save-money.png",
		alt: "Person balancing a coin on a hand",
		title: "Person balancing a coin on a hand",
	},

	{
		iconSrc: "/icons/stock-chart.png",
		alt: "Person showing a stock chart",
		title: "Person showing a stock chart",
	},
	{
		iconSrc: "/icons/tick.png",
		alt: "Person showing a tick icon",
		title: "Person showing a tick icon",
	},
	{
		iconSrc: "/icons/wallet.png",
		alt: "Person showing off a wallet",
		title: "Person showing off a wallet",
	},
];

export const updatedProfileIcons = [];

export const currencyOptions: CurrencyType[] = [
	{ code: "USD", name: "United States Dollar", symbol: "$" },
	{ code: "EUR", name: "Euro", symbol: "€" },
	{ code: "GBP", name: "British Pound", symbol: "£" },
	{ code: "JPY", name: "Japanese Yen", symbol: "¥" },
	{ code: "CNY", name: "Chinese Yuan", symbol: "CN¥" },
	{ code: "AUD", name: "Australian Dollar", symbol: "A$" },
	{ code: "CAD", name: "Canadian Dollar", symbol: "CA$" },
	{ code: "CHF", name: "Swiss Franc", symbol: "CHF" },
	{ code: "INR", name: "Indian Rupee", symbol: "₹" },
	{ code: "KRW", name: "South Korean Won", symbol: "₩" },
	{ code: "BRL", name: "Brazilian Real", symbol: "R$" },
	{ code: "ZAR", name: "South African Rand", symbol: "ZAR" },
	{ code: "SEK", name: "Swedish Krona", symbol: "SEK" },
	{ code: "NOK", name: "Norwegian Krone", symbol: "NOK" },
	{ code: "DKK", name: "Danish Krone", symbol: "kr" },
	{ code: "MXN", name: "Mexican Peso", symbol: "$" },
	{ code: "RUB", name: "Russian Ruble", symbol: "RUB" },
	{ code: "SGD", name: "Singapore Dollar", symbol: "S$" },
	{ code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
	{ code: "NZD", name: "New Zealand Dollar", symbol: "$" },
	{ code: "TRY", name: "Turkish Lira", symbol: "₺" },
	{ code: "AED", name: "United Arab Emirates Dirham", symbol: "د.إ" },
	{ code: "SAR", name: "Saudi Riyal", symbol: "ر.س" },
	{ code: "THB", name: "Thai Baht", symbol: "฿" },
	{ code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
	{ code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
	{ code: "PLN", name: "Polish Zloty", symbol: "zł" },
	{ code: "CZK", name: "Czech Koruna", symbol: "Kč" },
	{ code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
	{ code: "ARS", name: "Argentine Peso", symbol: "$" },
];
